swagger: "2.0"
info:
  description: Swagger file para descrição da API de Background Check. Esta é uma POC do produto, cujo objetivo é realizar uma verificação do cliente, a fim de compreender sua confiabilidade.
  version: "1.0.0"
  title: Background Check API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1"
# Paths supported by the server application
paths:
  /background/{nome}:
    get:
      operationId: "api.check"
      parameters:
        - in: path
          name: nome
          required: true
          type: string
      tags:
        - "Background Check (STF, STJ, Jusbrasil, Facebook e Google)"
      summary: "Listagem de Possíveis Processos e Crimes"
      description: "Leia a lista de informações"
      responses:
        200:
          description: "Sucesso na leitura do site e extração dos dados."
          schema:
            type: "array"
            items:
              properties:
                Background:
                  type: "string"